---
################################################################################
#
# Description
#

Description: >-
  Template to create the RDS resources necessary for the application
  Version : 2017-01-27
  Author: John M.

################################################################################
#
# Parameters
#


################################################################################
#
# CONDITIONS
#


################################################################################
#
# MAPPINGS
#



################################################################################
#
# RESOURCES
#

Resources:

  ##############################################################################
  #
  # The LambdaFunctions
  #


  lambdaSetRdsMasterCreds:
    Type: AWS::CloudFormation::CustomResource
    Version: '1.0'
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:eu-west-1:${AWS::AccountId}:function:setRdsMasterCreds'
      KeyId: "b5051cc3-78d5-4a22-9a5f-c7709602ab0c"
      StackName: !Ref AWS::StackName
      TableName: 'rds_dev'


  lambdaGetDBPassword:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: lambdaSetRdsMasterCreds
    Version: '1.0'
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:eu-west-1:${AWS::AccountId}:function:getRdsMasterCreds'
      StackName: !Ref AWS::StackName
      TableName: 'rds_dev'


  ##############################################################################
  #
  # The DB
  #



################################################################################
#
# OUTPUTS
#


Outputs:
  rdsUserName:
    Description: Name of the RDS Instance
    Value: !GetAtt [ lambdaGetDBPassword, 'username' ]

  rdsPassword:
    Description: Name of the RDS Instance
    Value: !GetAtt [ lambdaGetDBPassword, 'password' ]


################################################################################
#
# NEVER CHANGE
#

AWSTemplateFormatVersion: '2010-09-09'
